# Unified Video System Configuration

system:
  target_processing_time: 0.7  # Target processing time in seconds
  enable_gpu: true
  enable_quantum_mode: true
  device: "cuda"  # cuda or cpu
  log_level: "INFO"
  cache_dir: "./cache"
  output_dir: "./output"

# Neural predictive cache settings
neural_cache:
  enabled: true
  cache_size_gb: 10
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
  similarity_threshold: 0.92
  preload_common_scenes: true
  max_cached_items: 10000

# Caption system configuration
caption:
  default_preset: "default"
  available_presets:
    - default
    - tiktok
    - youtube
    - cinematic
    - minimal
    - impact
  phoneme_sync: true
  gpu_rendering: true
  font_cache_size: 50
  
  # Default caption style
  default_style:
    font_family: "HelveticaTextNow-ExtraBold"
    font_size: 100
    font_color: "white"
    display_mode: "one_word"
    position: "center"

# Beat synchronization settings
beat_sync:
  enabled: true  # Python 3.13 compatible LibrosaBeatDetector
  cache_analysis: true
  analysis_cache_dir: "./cache/beat_analysis"
  min_tempo: 60
  max_tempo: 180
  sample_rate: 22050
  hop_length: 512
  
  # Dynamic cut durations (in seconds)
  cut_durations:
    explosive: 0.4
    high: 0.6
    medium: 1.2
    low: 2.875
  
  # Semantic state energy mappings
  semantic_states:
    PEACEFUL_MEDITATION: ["low", "medium"]
    SPIRITUAL_AWAKENING: ["medium", "high", "explosive"]
    INNER_STRUGGLE: ["medium", "high"]
    JOYFUL_CELEBRATION: ["high", "explosive"]
    TRANSCENDENT_FLOW: ["medium", "high"]
    CONTEMPLATIVE_WISDOM: ["low", "medium"]

# Performance optimization settings
performance:
  parallel_workers: 4
  batch_size: 32
  gpu_memory_mb: 4096
  cpu_threads: 8
  enable_mixed_precision: true
  enable_zero_copy: true
  enable_memory_pinning: true
  cuda_streams: 4

# Audio settings
audio:
  sample_rate: 44100
  format: "mp3"
  bitrate: "192k"
  normalize: true

# Video settings
video:
  resolution: "1920x1080"  # Default, can be "1080x1920" for TikTok
  fps: 30
  codec: "libx264"
  preset: "fast"
  crf: 23

# AI integration settings
ai:
  enable_ai_enhancements: true
  openai_api_key: "${OPENAI_API_KEY}"
  anthropic_api_key: "${ANTHROPIC_API_KEY}"
  fallback_to_local: true
  max_retries: 3
  timeout: 30

# Paths and directories
paths:
  models_dir: "./models"
  fonts_dir: "./fonts"
  temp_dir: "./temp"
  logs_dir: "./logs" 